/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Task {
  uuid: Generated<string>;
  todo_uuid: string;
  position: number;
  status: boolean;
  text: string;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface Todo {
  created_at: Date | null;
  position: number;
  title: string;
  updated_at: Date | null;
  uuid: Generated<string>;
}

export interface DB {
  task: Task;
  todo: Todo;
}
