/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Task {
  uuid: string;
  todo_uuid: string;
  position: number;
  status: number;
  text: string;
  created_at: Date | null;
  updated_at: Date | null;
}

export interface Todo {
  created_at: Date | null;
  position: number;
  title: string;
  updated_at: Date | null;
  uuid: string;
}

export interface DB {
  task: Task;
  todo: Todo;
}
